# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitgrove < Formula
  desc "Task-scoped git worktree workspaces for AI coding tools"
  homepage "https://github.com/catdevman/gitgrove"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/catdevman/gitgrove/releases/download/v0.5.0/gitgrove_darwin_amd64.tar.gz"
      sha256 "a52ab7c49946f03597360f482f5463e84af02eea311c8d86e209c6af4a431ff8"

      define_method(:install) do
        bin.install "gitgrove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/catdevman/gitgrove/releases/download/v0.5.0/gitgrove_darwin_arm64.tar.gz"
      sha256 "4b78605ec127f0fd4c4b9f78940d9e8f8cdf5c1cfd154eb19bc4a77c056ff262"

      define_method(:install) do
        bin.install "gitgrove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/catdevman/gitgrove/releases/download/v0.5.0/gitgrove_linux_amd64.tar.gz"
      sha256 "90327f6451275328c3733d754d0ebce35676b545b23c230d81bad41b661d1244"
      define_method(:install) do
        bin.install "gitgrove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/catdevman/gitgrove/releases/download/v0.5.0/gitgrove_linux_arm64.tar.gz"
      sha256 "7f39a3bceaf980740e6af187590088e627eba6c0a5e1586c7c1111136b330a8e"
      define_method(:install) do
        bin.install "gitgrove"
      end
    end
  end
end
