# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitgrove" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "d8434c25259a251f7cd1d12be78ce7449d3ce1f240723936df3b053e91c4b760"
      url "https://github.com/catdevman/gitgrove/releases/download/v#{version}/gitgrove_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f44e72efcdfa914cbfda298faf1abea1d3749ac924b140db58c62984d086d48"
      url "https://github.com/catdevman/gitgrove/releases/download/v#{version}/gitgrove_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0cc414b5c7134103e30bdcbe1c176d5a0871ce9d4d6cdc60bc8ad6a0d2674f89"
      url "https://github.com/catdevman/gitgrove/releases/download/v#{version}/gitgrove_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a21f57872eaa0e4eea0cd2793769ddb2f6e4cc5a16040e96fcb93445f4515f2c"
      url "https://github.com/catdevman/gitgrove/releases/download/v#{version}/gitgrove_linux_arm64.tar.gz"
    end
  end

  name "gitgrove"
  desc "Task-scoped git worktree workspaces for AI coding tools"
  homepage "https://github.com/catdevman/gitgrove"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitgrove"

  # No zap stanza required

end
