# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitgrove < Formula
  desc "Task-scoped git worktree workspaces for AI coding tools"
  homepage "https://github.com/catdevman/gitgrove"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/catdevman/gitgrove/releases/download/v0.6.0/gitgrove_darwin_amd64.tar.gz"
      sha256 "d28708ef629cdb6883fb4e899f86eafb7d533a0b142ee145e8b98e60a6e98bf5"

      define_method(:install) do
        bin.install "gitgrove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/catdevman/gitgrove/releases/download/v0.6.0/gitgrove_darwin_arm64.tar.gz"
      sha256 "e1b869e9bc7267649c9ec97cd48842456e8d8de1684e8b86d1b45c0b28c6072c"

      define_method(:install) do
        bin.install "gitgrove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/catdevman/gitgrove/releases/download/v0.6.0/gitgrove_linux_amd64.tar.gz"
      sha256 "55b46e4a0e0b87692b96a7e5c7b54b16c22c85455c90bdff675b4459491d615f"
      define_method(:install) do
        bin.install "gitgrove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/catdevman/gitgrove/releases/download/v0.6.0/gitgrove_linux_arm64.tar.gz"
      sha256 "d562dc9be8e63630f5ff082521f14d11f6f724f292ca96c12668b830c028a324"
      define_method(:install) do
        bin.install "gitgrove"
      end
    end
  end
end
